### ISSUE TITLE
About dataset.

### ISSUE THREAD

**Issue by TomasAndersonFang** [flyboss/CQIL#1]
Hello author, when I download the dataset of CODEnn and replace files in the /data folder, I find that I can't execute the pipeline.py file because of missing train.json file.

**Comment by flyboss** [comment]
Hello, you can first try the CosBench dataset, replace files in the /data folder and execute CQIL directly.
As the CODEnn dataset has been processed by the original authors, you may convert its data format like examples in /data folder.
